const LOADER_CSS = String.raw`
.loading{position:fixed;inset:0;z-index:120;display:grid;place-items:center;background:#000;color:var(--paper);overflow:hidden;pointer-events:auto}.loading:before{content:'';position:absolute;inset:0;background:radial-gradient(circle at 72% 28%,rgba(255,0,0,.22),transparent 28rem),linear-gradient(135deg,#000 0%,#1c0000 48%,#000 100%)}.loading:after{content:'culture loading';position:absolute;left:clamp(18px,5vw,86px);bottom:clamp(22px,4vw,54px);font-family:Dirtyline,Impact,sans-serif;font-size:clamp(32px,6vw,94px);line-height:.75;color:transparent;-webkit-text-stroke:1px rgba(255,0,0,.42);opacity:.72}.loader-inner{position:relative;z-index:2;width:min(900px,calc(100% - 36px));display:grid;gap:clamp(28px,5vw,60px)}.loader-mark{font-family:var(--ui);font-size:clamp(30px,5vw,74px);font-weight:900;letter-spacing:-.04em;color:var(--red)}.loader-type{font-family:Dirtyline,Impact,sans-serif;font-size:clamp(70px,16vw,230px);line-height:.68;color:var(--paper);max-width:7ch}.loader-type em{display:block;color:var(--red);font-style:normal}.loader-row{display:grid;grid-template-columns:1fr auto;align-items:center;gap:18px}.loader-bar{height:2px;background:rgba(244,238,232,.16);overflow:hidden}.loader-bar span{display:block;width:0;height:100%;background:var(--red)}.loader-count{min-width:46px;text-align:right;font:11px var(--ui);letter-spacing:.13em;text-transform:uppercase;color:var(--muted)}html.is-loading body{cursor:progress}html.is-loading main,html.is-loading .topbar,html.is-loading .story-nav,html.is-loading .progress,html.is-loading .guide{visibility:hidden}.font-wait .display-title,.font-wait .kicker,.font-wait .chapter,.font-wait .chip,.font-wait .stage-meta,.font-wait .hero-media b,.font-wait .panel figcaption,.font-wait .deco,.font-wait .loader-type,.font-wait .loading:after{opacity:.001}`;

const LOADER_HTML = String.raw`<div class="loading" id="loading" aria-label="Loading UNMAD" aria-live="polite"><div class="loader-inner"><div class="loader-mark">UNMAD</div><div class="loader-type"><span>hold</span><em>signal.</em></div><div class="loader-row"><div class="loader-bar"><span></span></div><div class="loader-count" id="loaderCount">00</div></div></div></div>`;

const LOADER_SCRIPT = String.raw`document.documentElement.classList.add('is-loading','font-wait');`;

const LOADER_BOOT = String.raw`const loader=document.getElementById('loading'),loaderFill=loader?.querySelector('.loader-bar span'),loaderCount=document.getElementById('loaderCount');const fontReady=document.fonts?document.fonts.ready.catch(()=>{}):Promise.resolve();let loadProgress={v:0};gsap.to(loadProgress,{v:86,duration:1.15,ease:'power2.out',onUpdate:()=>{if(loaderFill)loaderFill.style.width=loadProgress.v+'%';if(loaderCount)loaderCount.textContent=String(Math.round(loadProgress.v)).padStart(2,'0')}});await Promise.race([fontReady,new Promise(r=>setTimeout(r,1800))]);document.documentElement.classList.remove('font-wait');await new Promise(r=>requestAnimationFrame(r));gsap.to(loadProgress,{v:100,duration:.34,ease:'power2.out',onUpdate:()=>{if(loaderFill)loaderFill.style.width=loadProgress.v+'%';if(loaderCount)loaderCount.textContent=String(Math.round(loadProgress.v)).padStart(2,'0')}});const loaderTl=gsap.timeline({delay:.12,onComplete:()=>{loader?.remove();document.documentElement.classList.remove('is-loading');ScrollTrigger.refresh()}});loaderTl.to('.loader-type span',{yPercent:-112,rotation:-3,duration:.72,ease:'power4.inOut'},0).to('.loader-type em',{yPercent:-112,rotation:3,duration:.72,ease:'power4.inOut'},.04).to('.loader-mark,.loader-row',{autoAlpha:0,y:-18,duration:.42},.18).to(loader,{clipPath:'polygon(0 0,100% 0,100% 0,0 12%)',duration:.82,ease:'power4.inOut'},.34);`;

const HERO_TRANSITION = String.raw`/*loader-hero-transition*/gsap.from('.hero-media',{clipPath:'polygon(0 48%,100% 40%,100% 58%,0 66%)',filter:'blur(10px)',duration:1.05,ease:'power4.out',delay:.66});gsap.from('.hero .deco',{autoAlpha:0,scale:.86,rotation:-10,duration:.9,stagger:.08,ease:'power3.out',delay:.78});`;

export function withLoader(html) {
  return html
    .replace('.progress{position:fixed;', `${LOADER_CSS}.progress{position:fixed;`)
    .replace('<body>\n  <div class="progress">', `<body>\n  ${LOADER_HTML}\n  <div class="progress">`)
    .replace('addEventListener(\'load\',()=>{gsap.registerPlugin(ScrollTrigger);', `${LOADER_SCRIPT}addEventListener('load',async()=>{gsap.registerPlugin(ScrollTrigger);${LOADER_BOOT}`)
    .replace("gsap.from('.hero .split span',{yPercent:112,rotation:2,duration:1.05,stagger:.1,ease:'power4.out'});", "gsap.from('.hero .split span',{yPercent:112,rotation:2,duration:1.05,stagger:.1,ease:'power4.out',delay:.54});" + HERO_TRANSITION)
    .replace("gsap.from('.hero .split span',{yPercent:112,rotation:2,duration:1.15,stagger:.1,ease:'power4.out'});", "gsap.from('.hero .split span',{yPercent:112,rotation:2,duration:1.15,stagger:.1,ease:'power4.out',delay:.54});" + HERO_TRANSITION);
}
